backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

site_url: https://soap.chrisandmami.com

collections:
  - name: soaps
    create: true
    extension: md
    folder: "content/soaps"
    format: frontmatter
    identifier_field: slug
    label_singular: Soap
    label: Soaps
    editor:
     preview: false
    fields:
      - { label: "URL slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Made Date", name: "date", widget: "date" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Content"
    name: "content"
    files:
      - file: "content/global.yml"
        label: "Global dictionary"
        name: "content"
        fields:
          - { label: "Homepage title", name: "homepageTitle", widget: "string" }
          - { label: "Header title", name: "headerTitle", widget: "string" }
          - { label: "Header subtitle", name: "headerSubtitle", widget: "string" }
          - { label: "Date prefix label", name: "datePrefixLabel", widget: "string" }
