backend:
  name: git-gateway
  branch: master

media_folder: static/image
public_folder: /image

collections:
  - name: "soaps"
    label: "Soaps"
    folder: "content/soaps"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Made Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
